### ISSUE TITLE
Use fleet api instead of cli

### ISSUE THREAD

**Issue by sstarcher** [nyxcharon/sensu-plugins-fleet#1]
https://github.com/CenturyLinkLabs/fleet-api

**Comment by nyxcharon** [comment]
Using the fleet api is certainly preferred but there were some issues with that.  
The fleet api isn't enabled by default, so you have to manually enable it https://coreos.com/docs/launching-containers/config/fleet-deployment-and-configuration/  
This is fine, but it looks like things like Deis ship with there own custom version of fleet instead of the standard version on CoreOS since they use it as  part of their back-end. As far as I could see there was no obvious way to enable the fleet API on Deis.

**Comment by sstarcher** [comment]
fleet-api version 0.9.0 writes directly to ETCD so it will work without the fleet api turned on.
I'm fairly certain Deis does not ship with a custom version of fleet.  The documentation you linked to works correctly on Deis 1.7.3.

**Comment by nyxcharon** [comment]
Tested working using fleet-api v0.9.0
